"""
CameraCalibration.py

Constants needed for pose estimation, such as the intrinsic camera matrix
and distortion coefficients. These were generated using
cv2.aruco.calibrateCameraCharuco

Created by Liam McKinney

Created 10/07/2023
Revised 10/19/2023
    -Added comments (Liam McKinney)
"""
import numpy as np

# intrinsic camera mtx. Generated by openCV, do not touch.
cameraMtx = np.array(
    [[1.10792216e+03, 0.00000000e+00, 6.64911260e+02],
     [0.00000000e+00, 1.10792216e+03, 4.49236496e+02],
     [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

# distortion coefficients for the camera. Also do not touch.
distortionCoeffs = np.array(
      [[-5.11419022e+00],
       [ 1.74472342e+01],
       [-2.13170076e-03],
       [-9.14366622e-04],
       [-3.51910149e+01],
       [-5.07287185e+00],
       [ 1.73451614e+01],
       [-3.52756075e+01],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00]])